-- Create all research tables

CREATE TABLE IF NOT EXISTS JOURNAL (
    DEPARTMENT_ID INT NOT NULL,
    AUTHORS VARCHAR(500),
    YEAR_OF_PUBLICATION VARCHAR(10),
    TITLE VARCHAR(500),
    JOURNAL_NAME VARCHAR(300),
    VOLUME_PAGE_NUMBER VARCHAR(100),
    ISSN VARCHAR(50),
    IMPACT_FACTOR VARCHAR(20),
    ID INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS CONFERENCE (
    DEPARTMENT_ID INT NOT NULL,
    YEAR_OF_PUBLICATION VARCHAR(10),
    AUTHOR VARCHAR(500),
    TITLE VARCHAR(500),
    CONFERENCE_NAME VARCHAR(300),
    VOLUME_PAGE_COUNT VARCHAR(100),
    ORGANIZED_BY VARCHAR(300),
    PLACE_OF_CONFERENCE VARCHAR(200),
    ID INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS BOOKCHAPTER (
    DEPARTMENT_ID INT NOT NULL,
    YEAR_OF_PUBLICATION VARCHAR(10),
    AUTHOR VARCHAR(500),
    CHAPTER_TITLE VARCHAR(500),
    BOOK_TITLE VARCHAR(500),
    PUBLISHER VARCHAR(300),
    ISSN VARCHAR(50),
    ID INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS FUNDEDRESEARCHPROJECT (
    DEPARTMENT_ID INT NOT NULL,
    PRINCIPAL_INVESTIGATOR VARCHAR(300),
    CO_INVESTIGATOR VARCHAR(300),
    TITLE VARCHAR(500),
    FUNDING_AGENCY VARCHAR(300),
    AMOUNT VARCHAR(50),
    DURATION VARCHAR(100),
    YEAR VARCHAR(10),
    ID INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS RESEARCHPROPOSALSUBMITTED (
    DEPARTMENT_ID INT NOT NULL,
    PRINCIPAL_INVESTIGATOR VARCHAR(300),
    CO_INVESTIGATOR VARCHAR(300),
    TITLE VARCHAR(500),
    FUNDING_AGENCY VARCHAR(300),
    AMOUNT VARCHAR(50),
    YEAR VARCHAR(10),
    ID INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS CONSULTANCY (
    DEPARTMENT_ID INT NOT NULL,
    FACULTY_NAME VARCHAR(300),
    ORGANIZATION VARCHAR(300),
    CONSULTANCY_PROVIDED VARCHAR(500),
    AMOUNT VARCHAR(50),
    YEAR VARCHAR(10),
    ID INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS PRODUCTDEVELOPMENT (
    DEPARTMENT_ID INT NOT NULL,
    FACULTY_NAME VARCHAR(300),
    PRODUCT_NAME VARCHAR(300),
    DESCRIPTION VARCHAR(1000),
    YEAR VARCHAR(10),
    ID INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS PATENT (
    DEPARTMENT_ID INT NOT NULL,
    INVENTOR_NAME VARCHAR(300),
    TITLE VARCHAR(500),
    PATENT_NUMBER VARCHAR(100),
    STATUS VARCHAR(50),
    YEAR VARCHAR(10),
    ID INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS FDPWORKSHOPSEMINAR (
    DEPARTMENT_ID INT NOT NULL,
    FACULTY_NAME VARCHAR(300),
    PROGRAM_NAME VARCHAR(300),
    PROGRAM_TYPE VARCHAR(100),
    ORGANIZED_BY VARCHAR(300),
    DURATION VARCHAR(100),
    YEAR VARCHAR(10),
    ID INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS MOUCS (
    DEPARTMENT_ID INT NOT NULL,
    ORGANIZATION VARCHAR(300),
    PURPOSE VARCHAR(500),
    DATE_OF_SIGNING VARCHAR(20),
    DURATION VARCHAR(100),
    ID INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS ACHIEVEMENTSANDAWARDS (
    DEPARTMENT_ID INT NOT NULL,
    FACULTY_STUDENT_NAME VARCHAR(300),
    ACHIEVEMENT VARCHAR(500),
    AWARD_BY VARCHAR(300),
    YEAR VARCHAR(10),
    ID INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS MOUS (
    DEPARTMENT_ID INT NOT NULL,
    ORGANIZATION VARCHAR(300),
    PURPOSE VARCHAR(500),
    DATE_OF_SIGNING VARCHAR(20),
    VALIDITY VARCHAR(100),
    ID INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS FUNDEDSTUDENTPROJECT (
    DEPARTMENT_ID INT NOT NULL,
    STUDENT_NAME VARCHAR(300),
    PROJECT_TITLE VARCHAR(500),
    FUNDING_AGENCY VARCHAR(300),
    AMOUNT VARCHAR(50),
    YEAR VARCHAR(10),
    ID INT AUTO_INCREMENT PRIMARY KEY
);